# Generated by Django 5.1.1 on 2024-10-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_feedback_post_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='lore',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
