# Generated by Django 5.1.1 on 2024-10-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lore_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lore',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
